#pragma kernel CSMain

float Scale;
float Height;
float Width;
int OffsetX;
int OffsetY;
Texture2D<float4> Input;
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float2 idx = round(id.xy*Scale);

    if (idx.x-OffsetX < Width && idx.y-OffsetY < Height && idx.x-OffsetX >= 0 && idx.y-OffsetY >= 0)
    {
        Result[id.xy] = pow(Input[uint2(idx.x-OffsetX,idx.y-OffsetY)],1.0f/2.2f);
    }
    else
    {
        Result[id.xy] = 0;
    }
}
